# Generated by Django 4.2.8 on 2024-05-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_dates',
            new_name='release_date',
        ),
    ]
