# Generated by Django 4.2.8 on 2024-05-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_release_dates_movie_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='age_rating',
            new_name='certification',
        ),
    ]
